FROM jupyter/scipy-notebook 
WORKDIR /srv/jupyterhub

RUN mkdir -p /srv/jupyterhub/data  
RUN chown -R jovyan:users /srv/jupyterhub
RUN python3 -m pip install --no-cache-dir \
    psycopg2-binary \    
    dockerspawner \
    jupyterhub-nativeauthenticator
    
COPY jupyterhub_config.py /srv/jupyter/jupyterhub_config.py
CMD ["jupyterhub", "-f", "/srv/jupyterhub/jupyterhub_config.py"]

