services:
  jupyterhub:
    build:
      context: .
      dockerfile: Dockerfile.jupyterhub
    restart: always
    image: jupyterhub
    container_name: jupyterhubtest
    networks:
      - jupyterhub-networktest
    volumes:
      - "./jupyterhub_config.py:/srv/jupyterhub/jupyterhub_config.py"
      - "/var/run/docker.sock:/var/run/docker.sockk:rw"
      - "jupyterhub-data:/srv/jupyterhub/data"
    ports:
      - "35003:8000"

volumes:
  jupyterhub-data:


networks:
  jupyterhub-network:
    name: jupyterhubtest







